spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 90079091124-rmkh10vsnapnj9kp7abrao82mqiuvkoq.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: 5xG_BVFccv28y4_Ppx36
            client-secret: UxxkfVZ_6t
            redirect-uri: https://qjszhpthasawfqrk.tunnel-pt.elice.io/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 3766b103b2245fe1d6598d2841f913f9
            client-secret: sWABsUSpcr8ssb9aiXzsmNyf7nOVMsAn
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jwt:
    secretKey: "yourverylongsecretkeyshouldbe64bytesormore1234567890"
    accessTokenExpiration: 3600000
    refreshTokenExpiration: 604800000
    accessTokenHeader: "Authorization"
    refreshTokenHeader: "Authorization-refresh"

  mail:
    host: smtp.gmail.com
    port: 587
    username: sktkeh@gmail.com
    password: slhp nraw upks wzho
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true